[options]
	LOG_ALL = true  # Log all chat to console?
	START_MSG = false  # Send a message to systemlog on starup?
	EXC_MSG = true  # Send exception messages to systemlog?
	LOG_PPR = true  # Log all chat to a file?

[twitch]
	channel = "controlmypc" # The channel to listen for commands on
    oauth_token = "no." # pretty much password to twitch

[api]
	mod = "https://api.cmpc.live/mods.txt" # moderator command access
	dev = "https://avpi.cmpc.live/devs.txt" # developer command access
	useragent = "CMPC script, https://cmpc.live" # "who are we" - this also sends in the discord webhooks

[discord]
	chatalerts = "https://discordapp.com/api/webhooks/741306005589327952/RMDc8zdyYG1BNuLjL2EDUIYVNwCJoJgwld8G8czXEwnp9kv_oGLMmv77RG5AoubrgfW8"
	chatrelay = "https://discordapp.com/api/webhooks/741316193369194506/slrRQYiTHPP6uNPeIflzIBuw6SQ5cZnsd_E6YHvl6BowBp-BPEVRl_cj0pN3TpYcxPcl"
	modtalk = "https://discordapp.com/api/webhooks/741311244308578392/7azdTbjAljUT0PTjBkTJzddh4i4vTj1H-_A1zJJVMZEYOIGWsP_1e60vTIJK-PQTOhEk"
	devtalk = "https://discordapp.com/api/webhooks/754130531188342909/WXK8aAiNyYPwLJgCMntBGEvewvmzdCoYba5TdVl_9Vy6jZfbKkrHb3OI1gZMJr5rbWJJ"
	botstat = "https://discordapp.com/api/webhooks/741343798285697126/_XYbtaaGAyRb5rgJMqNuph6DcHHxfMs7Ast12wDUZt1EWwfdsCbszem_ZuM79WWSlQsT"
	systemlog = "https://discord.com/api/webhooks/768300258257666069/shB15CV45CHVBW9QCOPUMIbX8lp3UV_twN2da5_ZWa2yCM59aa5LN5BDlFs0d0_QkXyi"

