[options]
	LOG_ALL = true  # Log all chat to console?
	START_MSG = false  # Send a message to systemlog on startup?
	EXC_MSG = true  # Send exception messages to systemlog?
	LOG_PPR = true  # Log all chat to a file?
	DEPLOY = "Debug" # Either "Production" or "Debug"
	LOGGER_LEVEL = "info" # non-case sensitive, sets logger level, most common are 'info' and 'debug'
                          # see https://docs.python.org/3/library/logging.html#levels

[twitch] # production example shown below
	username = "cmpcserver" # The channel to log in as
    oauth_token = "" # pretty much password to twitch
    api_client_id = "zvlttmj8jah002ucbqbpt1lkuq4oj3"  # used for getting info about users from the twitch api
                                                      # client id for the twitch app your got your oauth key from
	channel_to_join = "controlmypc" # Twitch channel to watch chat for

[api]
	apiconfig = "https://api.cmpc.live/apiconfig.json" # website to handle the dev and mod lists
	useragent = "CMPCscript (+https://cmpc.live/)" # "who are we" - this also sends in the discord webhooks
	panelapikey = "" # Panel API key for chatbot control
    panelapiendpoint = "https://panel.dukthosting.net/api/client/servers/xxxxx/power"

[discord]
	chatalerts = "https://discordapp.com/api/webhooks/xxxxx/xxxxx"
	chatrelay = "https://discordapp.com/api/webhooks/xxxxx/xxxxx"
	modtalk = "https://discordapp.com/api/webhooks/xxxxx/xxxxx"
	devtalk = "https://discordapp.com/api/webhooks/xxxxx/xxxxx"
	botstat = "https://discordapp.com/api/webhooks/xxxxx/xxxxx"
	systemlog = "https://discord.com/api/webhooks/xxxxx/xxxxx"
	modalertping = "<@&xxxxxxxxxxxxxxxxxx>"
