[options]
	LOG_ALL = true  # Log all chat to console?
	START_MSG = false  # Send a message to systemlog on startup?
	EXC_MSG = true  # Send exception messages to systemlog?
	LOG_PPR = true  # Log all chat to a file?
	DEPLOY = "Debug" # Either "Production" or "Debug"

[twitch]
	channel = "controlmypc" # The channel to listen for commands on
    oauth_token = "" # pretty much password to twitch

[api]
	mod = "https://api.cmpc.live/mods.txt" # moderator command access
	dev = "https://api.cmpc.live/devs.txt" # developer command access
	apiconfig = "https://api.cmpc.live/apiconfig.json"
	useragent = "CMPCscript (+https://cmpc.live/)" # "who are we" - this also sends in the discord webhooks
	panelapikey = "" # Panel API key for chatbot control
    panelapiendpoint = "https://panel.dukthosting.net/api/client/servers/9119ce36-8f28-4824-8b10-99a34d05e696/power"

[discord]
	chatalerts = "https://discordapp.com/api/webhooks/741306005589327952/RMDc8zdyYG1BNuLjL2EDUIYVNwCJoJgwld8G8czXEwnp9kv_oGLMmv77RG5AoubrgfW8"
	chatrelay = "https://discordapp.com/api/webhooks/741316193369194506/slrRQYiTHPP6uNPeIflzIBuw6SQ5cZnsd_E6YHvl6BowBp-BPEVRl_cj0pN3TpYcxPcl"
	modtalk = "https://discordapp.com/api/webhooks/741311244308578392/7azdTbjAljUT0PTjBkTJzddh4i4vTj1H-_A1zJJVMZEYOIGWsP_1e60vTIJK-PQTOhEk"
	devtalk = "https://discordapp.com/api/webhooks/754130531188342909/WXK8aAiNyYPwLJgCMntBGEvewvmzdCoYba5TdVl_9Vy6jZfbKkrHb3OI1gZMJr5rbWJJ"
	botstat = "https://discordapp.com/api/webhooks/741343798285697126/_XYbtaaGAyRb5rgJMqNuph6DcHHxfMs7Ast12wDUZt1EWwfdsCbszem_ZuM79WWSlQsT"
	systemlog = "https://discord.com/api/webhooks/768300258257666069/shB15CV45CHVBW9QCOPUMIbX8lp3UV_twN2da5_ZWa2yCM59aa5LN5BDlFs0d0_QkXyi"

